"""Fix derived_from_id with named constraint

Revision ID: 00ae2740afa0
Revises: eb583e22961a
Create Date: 2025-05-16 01:01:25.384084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '00ae2740afa0'
down_revision = 'eb583e22961a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_image')
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('derived_from_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_image_derived_from', 'image', ['derived_from_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('original_image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_post_original_image', 'image', ['original_image_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_original_image', type_='foreignkey')
        batch_op.drop_column('original_image_id')
        batch_op.drop_column('source_type')

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint('fk_image_derived_from', type_='foreignkey')
        batch_op.drop_column('derived_from_id')

    op.create_table('_alembic_tmp_image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('tool_used', sa.VARCHAR(length=64), nullable=True),
    sa.Column('parameters', sqlite.JSON(), nullable=True),
    sa.Column('derived_from_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['derived_from_id'], ['image.id'], name='fk_image_derived_from'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
