"""Changed Post column Created_at -> timestamp

Revision ID: 33973bc91138
Revises: 7ed305f15446
Create Date: 2025-05-05 11:02:25.231078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33973bc91138'
down_revision = '7ed305f15446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
