"""Added subtitle to Post, set up Image relationship

Revision ID: c10a18d599da
Revises: 33973bc91138
Create Date: 2025-05-12 21:19:11.110560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10a18d599da'
down_revision = '33973bc91138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
