"""Image now stores its source and (if a tool was used) parameters to make it

Revision ID: eb583e22961a
Revises: c10a18d599da
Create Date: 2025-05-15 14:15:15.653050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb583e22961a'
down_revision = 'c10a18d599da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('tool_used', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('parameters', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('parameters')
        batch_op.drop_column('tool_used')
        batch_op.drop_column('source_type')

    # ### end Alembic commands ###
